# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-SMTP-SSL
version:      1.01
version_from: lib/Net/SMTP/SSL.pm
installdirs:  site
requires:
    IO::Socket::SSL:               
    Net::SMTP:                     
    Test::More:                    0.47

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
